FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /opt/app/model

COPY model/src ./src
COPY model/pom.xml pom.xml

RUN mvn clean install

WORKDIR /opt/app/server

COPY server/src ./src
COPY server/pom.xml pom.xml

RUN mvn clean install

EXPOSE 8181

CMD ["java", "-jar", "target/server-0.0.1-SNAPSHOT.jar"]
