name: csm

services:
  csm_client:
    build:
      context: .
      dockerfile: ./dockerFiles/Dockerfile_client
    stdin_open: true
    tty: true
    networks:
      - frontend
    container_name:
      csm_client_container
    depends_on:
      - csm_server
  csm_server:
    build:
      context: .
      dockerfile: ./dockerFiles/Dockerfile_server
    networks:
      - frontend
      - backend
    container_name:
      csm_server_container
    depends_on:
      - csm_mongo
  csm_mongo:
    image: mongo
    networks:
      - backend
    container_name: csm_mongo
    volumes:
      - csm_mongodb_vol:/data/db

volumes:
  csm_mongodb_vol:
    external: true

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge